// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEdU8M3dBrjzcHPS6tacNZYct0cv5ACU4',
    appId: '1:88871952660:web:17dd1d83a968d3e20ba201',
    messagingSenderId: '88871952660',
    projectId: 'evalu2-2262a',
    authDomain: 'evalu2-2262a.firebaseapp.com',
    databaseURL: 'https://evalu2-2262a-default-rtdb.firebaseio.com',
    storageBucket: 'evalu2-2262a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ts1QJ_GkY2rF63KfpMfIcvaS7zi32tQ',
    appId: '1:88871952660:android:44e04fbf29d263d60ba201',
    messagingSenderId: '88871952660',
    projectId: 'evalu2-2262a',
    databaseURL: 'https://evalu2-2262a-default-rtdb.firebaseio.com',
    storageBucket: 'evalu2-2262a.firebasestorage.app',
  );
}
